name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          gem install bundler
          bundle install
          bundle exec rake assets:precompile RAILS_ENV=production
          docker build . --file Dockerfile --tag gotocompany/gate:${{ github.ref_name }}
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker image
        run: docker push gotocompany/gate:${{ github.ref_name }}
